### ISSUE TITLE
Checking WITH_OPENSSL flag might not be correct

### ISSUE THREAD

**Issue by ajindal1** [pytorch/builder#1272]
In this PR (https://github.com/pytorch/builder/pull/1262), for Python 3.11 there was a new flag added, WITH_OPENSSL. Later it is being checked whether the value of WITH_OPENSSL is empty or not. However, since the variable is only set for Python 3.11 case, it doesn't exist for other cases and the code fails because ```set -u``` is used (treat unset variables as error). I think this can be solved by either of two options:

1. Checking if the variable is set or not, which can be done by the below command as detailed in this link (https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash).
if [[ -z  ${WITH_OPENSSL+x} ]]; then

2. Setting WITH_OPENSSL="" in case it is not set in the else statement while setting it for Python 3.11.

**Comment by ptrblck** [comment]
I'm seeing the same issues in https://github.com/pytorch/builder/pull/1271/ and was already starting to debug and agree with the description.

CC @atalman

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/builder/pull/1276
