### ISSUE TITLE
Can't use torchvision or torchaudio binaries from pytorch-nightly conda channel with custom built PyTorch 2.0.0 binaries

### ISSUE THREAD

**Issue by dkey-amazon** [pytorch/builder#1326]
For context, I'm working on custom-building binaries here at AWS for PyTorch 2.0.0.  We have some custom modifications we're trying to make, so we can't use the PyTorch binaries in the standard `pytorch`, `pytorch-test`, or `pytorch-nightly` conda channels.  Our goal is to create a custom conda channel we can use, with our custom PyTorch binaries.

Where I'm running into issues is trying to use the `pytorch-nightly` dev binaries for TorchAudio and Torch vision with my custom PyTorch 2.0.0 binaries.  When I try and create a conda environment using my custom-built PyTorch 2.0.0 binaries, I get the following error:

```
Looking for: ['python=3.8', 'pytorch==2.0.0=aws_py3.8_cuda11.8_cudnn8.7.0_0', 'pytorch-cuda=11.8', 'torchvision', 'torchaudio']

Could not solve for environment specs
Encountered problems while solving:
  - nothing provides pytorch 2.0.0.dev20230220 needed by torchvision-0.15.0.dev20230223-py310_cu117
  - nothing provides pytorch 2.0.0.dev20230220 needed by torchaudio-2.0.0.dev20230223-py310_cu117
```

Here are the files in my local test channel:

```
$ls -la | awk '{print $9}'

.
..
aws-ofi-nccl-1.5.0-aws_0.tar.bz2
.cache
current_repodata.json
current_repodata.json.bz2
index.html
pytorch-2.0.0-aws_py3.10_cuda11.7_cudnn8.5.0_0.tar.bz2
pytorch-2.0.0-aws_py3.10_cuda11.8_cudnn8.7.0_0.tar.bz2
pytorch-2.0.0-aws_py3.8_cuda11.7_cudnn8.5.0_0.tar.bz2
pytorch-2.0.0-aws_py3.8_cuda11.8_cudnn8.7.0_0.tar.bz2
pytorch-2.0.0-aws_py3.9_cuda11.7_cudnn8.5.0_0.tar.bz2
pytorch-2.0.0-aws_py3.9_cuda11.8_cudnn8.7.0_0.tar.bz2
pytorch-cuda-11.7-h778d358_3.tar.bz2
pytorch-cuda-11.8-h7e8668a_3.tar.bz2
pytorch-mutex-1.0-cuda.tar.bz2
repodata_from_packages.json
repodata_from_packages.json.bz2
repodata.json
repodata.json.bz2
torchaudio-2.0.0.dev20230223-py310_cu117.tar.bz2
torchaudio-2.0.0.dev20230223-py310_cu118.tar.bz2
torchaudio-2.0.0.dev20230223-py38_cu117.tar.bz2
torchaudio-2.0.0.dev20230223-py38_cu118.tar.bz2
torchaudio-2.0.0.dev20230223-py39_cu117.tar.bz2
torchaudio-2.0.0.dev20230223-py39_cu118.tar.bz2
torchvision-0.15.0.dev20230223-py310_cu117.tar.bz2
torchvision-0.15.0.dev20230223-py310_cu118.tar.bz2
torchvision-0.15.0.dev20230223-py38_cu117.tar.bz2
torchvision-0.15.0.dev20230223-py38_cu118.tar.bz2
torchvision-0.15.0.dev20230223-py39_cu117.tar.bz2
torchvision-0.15.0.dev20230223-py39_cu118.tar.bz2
```

I am not sure how to get the dev torchvision and torchaudio binaries to properly link to my hand-made PyTorch 2.0.0 binaries.

Open Questions:
- Are there any RC binaries I could use directly with my custom PyTorch 2.0.0 conda binaries that will properly resolve conda dependencies when building a custom conda environment?
- Is there any documentation on how to create custom PyTorch 2.0.0 binaries for conda, and how those binaries should be used with the associated TorchAudio and TorchVision conda binaries available?
- Got any other recommendations or links to documentation that might help here?

Steps to reproduce:
- Create custom PyTorch 2.0.0 binaries using [pytorch-builder](https://github.com/pytorch/builder/tree/release/2.0).
- Create a local conda channel with those custom PyTorch 2.0.0 binaries as shown above.
- Try to create a conda environment using the dev TorchAudio and TorchVision binaries as listed from the `pytorch-nightly` conda channel.
- Observe the `Could not solve for environment specs` error above.

Thanks in advance for any help!

**Comment by roywei** [comment]
Hi @malfet @atalman we are a team at AWS building optimized PyTorch and package it in a conda channel, we ship this PyTorch to Meta AI Research team. Some optimizations include customized NCCL changes and making PyTorch to use AWS EFA hardware out of box. We are working on supporting PyTorch 2.0 RC builds, so far PyTorch builds are working fine for us, however we lack knowledge on how to build Torchvison and audio conda package. Any tips or documentation will help. Looking forward to collaborate and enable more community builds for PyTorch. Thanks!

**Comment by atalman** [comment]
@dkey-amazon @roywei If you build pytorch from source you will also need to rebuild torchvision and torchaudio. If you navigate to conda repo : https://anaconda.org/pytorch-nightly/torchvision/files?version=0.15.0.dev20230228
And open metadata info for our packages you will see it depends on particular version of nightly:

<img width="999" alt="Screenshot 2023-02-28 at 8 47 20 AM" src="https://user-images.githubusercontent.com/7563158/221873416-f69f0ed2-98f8-4255-8cc7-5d811a340d11.png">

For an example how to compile torchvision please take a look at this workflow:
https://github.com/pytorch/vision/actions/runs/4292971969/jobs/7480074737

**Comment by roywei** [comment]
Thank you so much for sharing! We will look into the workflow

**Comment by dkey-amazon** [comment]
Thank you for the information!  I'm having trouble viewing the logs though.  Is there a way to increase the log retention on these jobs?  I can't find a job run new enough where I can see the logs.  I just see the below error message, even on the most recent run [here](https://github.com/pytorch/vision/actions/runs/4313987839/jobs/7526473352).

```
 Error: The log was not found. It may have been deleted based on retention settings. 
```
