### ISSUE TITLE
Pip packaging and publishing improvements in pytorch wheels for better integration with poetry

### ISSUE THREAD

**Issue by juliusfrost** [pytorch/builder#1347]
Please see the issues described here: https://github.com/pytorch/pytorch/issues/76557

**Comment by jzazo** [comment]
I am not sure how or why, but `poetry add torch==1.13.1` installs all needed dependencies, but `poetry add torch==2.0.0` does not install necessary packages and does not work. Is there a way that works with poetry? Thanks.

**Comment by vit-zikmund** [comment]
I did a little investigation, trying to figure out if this would be feasible for a PR. Here's what I've found what might be done to get this further

## Investigation

- The main objective is to add the URL fragment (`#<hashname>=<hashvalue>`) to the Simple Repository package `index.html` described in [PEP503](https://peps.python.org/pep-0503/). The recommended hash algorithm is `sha256`, so we should aim for that.

- All the published files normally accessible from [download.pytorch.org/whl](https://download.pytorch.org/whl/index.html) are in fact hosted on this [public AWS S3 `pytorch` bucket](https://s3.console.aws.amazon.com/s3/buckets/pytorch) and most of the tooling I saw is built around it.

- The tool that generates these indexes sits in this repo as [`s3_management/manage.py`](https://github.com/pytorch/builder/blob/main/s3_management/manage.py). It does so by scanning select files ("objects" in the S3 jargon) in the bucket, generating the simple html pages from the object `key`s (that are the fully qualified paths respective to the bucket's root). This script is quite simple to read and modify and adding support for the hashes would surely go to the [`to_simple_package_html`](https://github.com/pytorch/builder/blob/60c79a85fb3a1dbe327a735f1f03e7f110ca0427/s3_management/manage.py#L232) method.

- The main challenge is where to get the file's `sha256` digest for the URL Fragment.

- More than a year ago AWS S3 [added support for computing/storing additional checksums](https://stackoverflow.com/a/72072473/921269), that also include the `sha256` algorithm. While there is a fairly easy way how to retrieve the checksum for an S3 object using the [`get_object_attributes`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_object_attributes.html) call, there's a catch.

- The hash needs to be uploaded along with the content for it to be there. There's a [couple ways how to do that](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html), however none involves the locally popular `aws s3 cp` command. It seems there might be an stand-in alternative using `aws s3api put-object` [described in the issue requesting support in `aws s3 cp`](https://github.com/aws/aws-cli/issues/6750#issuecomment-1195959947) :slightly_smiling_face: 

- There are various little scripts doing the uploads to S3 scattered across the repo and for a foreigner like me it's pretty hard to determine what scripts are really used and how. This would need to be identified to target the changes.

## Challenges
- [ ] Enable `sha256` checksums along with package uploads.<br />_Proper places need to be identified and the feasibility of the solution verified._
- [ ] Add checksum retieval & publishing logic to [`s3_management/manage.py`](https://github.com/pytorch/builder/blob/main/s3_management/manage.py).<br />_This is rather easily done once the hashes are in S3._

**Comment by vit-zikmund** [comment]
Tagging @seemethere & @malfet with a humble request for comments. Thank you!

**Comment by thejcannon** [comment]
I think the title likely should reflect what this issue truly represents which is PEP 503-supported hashes on certain package URLs
