### ISSUE TITLE
magma version for cuda 12

### ISSUE THREAD

**Issue by cdeepali** [pytorch/builder#1372]
Magma v2.7.1 adds support for cuda 12 - https://bitbucket.org/icl/magma/src/965af99469cf9b5fdd584b38a4d2911d21cb026c/ReleaseNotes#lines-29.  

So I think we need to update to magma 2.7.1 for cuda 12.

**Comment by ptrblck** [comment]
Magma builds for `2.6.1` are already provided via: https://github.com/pytorch/builder/pull/1368.
We are already testing an update to `2.7.1` to avoid the new patch, but don't have any results yet as we need to update the existing patches.

**Comment by pyang-aurora** [comment]
Thanks for keeping the dependencies up-to-date! 
Is there any progress in 2.7.1? It would be nice since that version supports newer CUDA architectures.

**Comment by zhanwenchen** [comment]
@ptrblck Any update on 2.7.1?

**Comment by ptrblck** [comment]
@zhanwenchen no updates, as we only did the initial testing, but dropped it as our focus is not on MAGMA but cuSOLVER.
I assume PRs are welcome in case you want to update MAGMA.
