### ISSUE TITLE
Unable to install okay-release in Dockerfile

### ISSUE THREAD

**Issue by ajindal1** [pytorch/builder#1573]
While running manywheel/Dockerfile with CUDA, the code is failing while installing okay-release package with the below error. I have tried using other versions as well but still getting the same error. Command used: 
```
GPU_ARCH_TYPE=cuda GPU_ARCH_VERSION=11.8 manywheel/build_docker.sh
```

Error details:
```
 > [cpu_final 6/7] RUN yum install -y http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-5.el7.noarch.rpm:
#53 1.357 Loaded plugins: fastestmirror, ovl
#53 1.546 Examining /var/tmp/yum-root-m4yUfP/okay-release-1-5.el7.noarch.rpm: okay-release-1-5.el7.noarch
#53 1.549 Marking /var/tmp/yum-root-m4yUfP/okay-release-1-5.el7.noarch.rpm to be installed
#53 1.549 Resolving Dependencies
#53 1.551 --> Running transaction check
#53 1.551 ---> Package okay-release.noarch 0:1-5.el7 will be installed
#53 1.618 --> Finished Dependency Resolution
#53 1.664
#53 1.664 Dependencies Resolved
#53 1.664
#53 1.664 ================================================================================
#53 1.664  Package          Arch       Version     Repository                        Size
#53 1.664 ================================================================================
#53 1.664 Installing:
#53 1.664  okay-release     noarch     1-5.el7     /okay-release-1-5.el7.noarch     3.1 k
#53 1.664
#53 1.664 Transaction Summary
#53 1.664 ================================================================================
#53 1.664 Install  1 Package
#53 1.664
#53 1.664 Total size: 3.1 k
#53 1.664 Installed size: 3.1 k
#53 1.664 Downloading packages:
#53 1.673 Running transaction check
#53 1.678 Running transaction test
#53 1.687
#53 1.687
#53 1.687 Transaction check error:
#53 1.687   Unknown error during transaction test in RPM
#53 1.687
#53 1.687 Error Summary
#53 1.687 -------------
#53 1.687
------
executor failed running [/bin/sh -c yum install -y http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-5.el7.noarch.rpm]: exit code: 1

```

**Comment by thiagocrepaldi** [comment]
@kit1980 @malfet would you be able to help with this error?

**Comment by kit1980** [comment]
Looks like an issue with downloading the RPM. Can you retry, maybe after cleaning docker cache?

**Comment by ajindal1** [comment]
@kit1980 Download step is working fine but installation step has an issue. I tried cleaning yum cache but didn't help. Also tried download and install step separately.

Cleaning cache:
```
71.20 Transaction check error:
71.20   Unknown error during transaction test in RPM
71.20
71.20 Error Summary
71.20 -------------
71.20
------
Dockerfile:150
--------------------
 148 |     RUN yum clean all
 149 |     RUN yum clean metadata
 150 | >>> RUN yum install -y http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-5.el7.noarch.rpm
 151 |     RUN yum install -y ninja-build
```

Download and install separately:
```
159.1 Running transaction test
159.1
159.1
159.1 Transaction check error:
159.1   Unknown error during transaction test in RPM
159.1
159.1 Error Summary
159.1 -------------
159.1
------
Dockerfile:149
--------------------
 147 |     # ninja
 148 |     RUN wget http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-5.el7.noarch.rpm
 149 | >>> RUN yum install -y okay-release-1-5.el7.noarch.rpm
 150 |     RUN yum install -y ninja-build
 151 |
--------------------
ERROR: failed to solve: process "/bin/sh -c yum install -y okay-release-1-5.el7.noarch.rpm" did not complete successfully: exit code: 1
```

**Comment by kit1980** [comment]
@ajindal1 What I mean is that the downloaded file may be corrupted, so the installation step fails.
Maybe it's something else.
You can try to add something like "RUN md5 okay-release-1-5.el7.noarch.rpm", and compare that with a manually downloaded file.

**Comment by ramcherukuri** [comment]
I have the same issue. 

$ md5sum okay-release-1-5.el7.noarch.rpm
473a3220bcc50350c55f82eb6142b1b2  okay-release-1-5.el7.noarch.rpm

$ rpm2cpio okay-release-1-5.el7.noarch.rpm | cpio -idmv
./etc/pki/rpm-gpg/RPM-GPG-KEY-OKAY
./etc/pki/rpm-gpg/RPM-GPG-KEY-okayinc
./etc/yum.repos.d/okay.repo
8 blocks


$ tree etc/
etc/
├── pki
│   └── rpm-gpg
│       ├── RPM-GPG-KEY-OKAY
│       └── RPM-GPG-KEY-okayinc
└── yum.repos.d
    └── okay.repo

**Comment by ajindal1** [comment]
I was getting the same MD5sum using local download and in pipeline:
In pipeline:
```
#57 [cpu_final  8/10] RUN md5sum okay-release-1-5.el7.noarch.rpm
#57 sha256:f4d34a8d4f88274effb12d7cb9cd59d42a9e7221669306f1a3a9fd67fc5f52ab
#57 0.436 473a3220bcc50350c55f82eb6142b1b2  okay-release-1-5.el7.noarch.rpm
#57 DONE 0.5s
```
Local:
```
$ md5sum okay-release-1-5.el7.noarch.rpm
473a3220bcc50350c55f82eb6142b1b2  okay-release-1-5.el7.noarch.rpm
```

One option I could find to install the okay-release package was to use rpm and do no signature check (there might be security risk associated with it). Another option which I am currently using it to just remove the line to install okay release as it doesn't affect the process and doesn't give any other error for me.

**Comment by ramcherukuri** [comment]
>> Another option which I am currently using it to just remove the line to install okay release as it doesn't affect the process and doesn't give any other error for me.

I am doing the same at my end and it works for me too.

**Comment by ajindal1** [comment]
Closing this issue as it is removed in this PR https://github.com/pytorch/builder/pull/1575.
