### ISSUE TITLE
`numpy v2.0.0rc1` on pytorch/ conda channel problem

### ISSUE THREAD

**Issue by k-dominik** [pytorch/builder#1776]
Dear maintainers,

recently (around April 3rd, 2024) `numpy v2.0.0rc1` was added to the pytorch conda channel.
Many users source `pytorch` from the _pytorch_ channel in addition to whatever else they need from _conda-forge_. It is also common practice to prefer "strict" dependency resolution, making _pytorch_ a higher priority channel than _conda-forge_. This hides package from lower priority channels if they are present in the _pytorch_ channel. Effectively, this now means users cannot get any `numpy==1` package anymore if _pytorch_ is included with higher priority.

I'm not sure about the reason numpy was uploaded here (probably for [pytorch-nightly](https://github.com/pytorch/builder/blob/7276365219beef9e60204aefe0d3d35f22cdce1d/conda/pytorch-nightly/meta.yaml#L33)), but it would be preferable to remove the `main` label from that package here and add it under some other label (or a different conda channel all together, light `pytorch-nightly` if this is for experimentation).

I reported a similar issue with libjpeg-turbo (#1679) in the past (which still persists).

It would be great to get this sorted :)

CC: @jakirkham

**Comment by jakirkham** [comment]
cc @rgommers (for awareness)

**Comment by rgommers** [comment]
Another label makes sense to me, since numpy 2.0.0rc1 is needed at build time but not at runtime. This is also what conda-forge did, see https://github.com/conda-forge/numpy-feedstock/pull/312 and https://anaconda.org/conda-forge/numpy/files.

**Comment by jakirkham** [comment]
@atalman does this plan sound reasonable to you? If so, what are the next steps here?

**Comment by albanD** [comment]
This should have been removed now as we don't need it in this channel (we used another channel for our build dependencies that require it)!
Can you confirm it is working as expected now?

**Comment by k-dominik** [comment]
Hi @albanD,

thank you so much for sorting this out - it works for me now as before.

Any chance on a similar fix for `libjpeg-turbo` on linux-64 (https://github.com/pytorch/builder/issues/1679)?

Cheers
Dominik

**Comment by jakirkham** [comment]
Thanks all! 🙏

Let's go ahead and close this out as resolved then

We can discuss `libjpeg-turbo` in issue: https://github.com/pytorch/builder/issues/1679
