### ISSUE TITLE
Nightly with debug symbols

### ISSUE THREAD

**Issue by bhack** [pytorch/builder#185]
Can we add a nightly build with enabled debug symbols?

Check https://github.com/pytorch/pytorch/issues/12448#issuecomment-431458808

**Comment by soumith** [comment]
@bhack we gave the reasons already on why we cant add a nightly with debug symbols enabled, in the original thread.

The binary size makes this untenable.

**Comment by bhack** [comment]
Is too big also only for the host code debug symbols?
