### ISSUE TITLE
Unable to build docker image from Builder Repo 

### ISSUE THREAD

**Issue by ajindal1** [pytorch/builder#1851]
Unable to build docker image from Builder Repo because of openssl download error. I am unable to download using the ftp link but www link is working for me. https://github.com/pytorch/builder/blob/4414fc69945b2eb918a4f3bfd87563f03498f3c4/manywheel/build_scripts/build_utils.sh#L4
Will create a PR to fix the issue.

To reproduce, run this command:
```
GPU_ARCH_TYPE=cuda GPU_ARCH_VERSION=11.8 manywheel/build_docker.sh
```

Error:
```
curl -LO https://ftp.openssl.org/source/old/1.1.1//openssl-1.1.1l.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ftp.openssl.org
```

**Comment by ajindal1** [comment]
cc: @malfet @atalman

**Comment by malfet** [comment]
@ajindal1 please sign CLA (on the PR) and it's good to go

**Comment by ajindal1** [comment]
already signed the CLA, the bot says it might take an hour for it to recognize.

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/builder/pull/1854
