### ISSUE TITLE
add conda recipe for torchaudio

### ISSUE THREAD

**Issue by faroit** [pytorch/builder#279]
there are many issues with users having difficulties building torchaudio extension. Maybe it would be good to provide conda builds?

I could create a recipe if that would be helpful.

**Comment by ezyang** [comment]
This is a good idea. @pjh5 is unfortunately away at the moment; I'm not sure what the most useful contribution we could make here is.

**Comment by soumith** [comment]
this seems reasonable to do. I have been doing some pre-work for this by adding `lame` support for `sox` in conda-forge: https://github.com/conda-forge/sox-feedstock/pull/18

We need to setup `torchaudio` with Azure pipelines to auto-build and auto-upload torchaudio packages as well, and then we'll be golden.

cc: @kostmo @pjh5 if you guys have any instructions on how one can setup a new repo with the necessary azure build config / pipelines, that'd be helpful, we would also want to do this soon for torchvision

**Comment by peterjc123** [comment]
@soumith It's easy to use. Just write the yaml config file and it will work. Here is the document for this: https://docs.microsoft.com/zh-cn/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema. And here is our example: https://github.com/pytorch/builder/blob/master/windows/azure-pipelines.yml.

**Comment by faroit** [comment]
is there some progress on this? I think the number of issues related to users having problems to install sox are getting way too many ;-)

**Comment by soumith** [comment]
https://github.com/pytorch/audio/tree/master/packaging
