### ISSUE TITLE
Where are Python 3.8 manywheel binaries built for nightlies?

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/builder#510]
Hi!

Thanks for making this repo public, it's very helpful. I've noticed that PyTorch is pushing pip manywheel nightlies for python 3.8, but it seems like 3.8 is missing from the configuration in `cron/` (e.g., 3.8 isn't defined here https://github.com/pytorch/builder/blob/master/cron/build_multiple.sh#L55 , among other places)

Am I missing something, or is the cron configuration to build 3.8 pip manywheels just not pushed yet?

Thanks in advance!

**Comment by soumith** [comment]
the cron folder is a bit outdated. now the binaries are triggered by CircleCI in this folder: https://github.com/pytorch/pytorch/tree/master/.circleci

Here's 3.8 spec: https://github.com/pytorch/pytorch/blob/master/.circleci/cimodel/data/binary_build_data.py#L36 and https://github.com/pytorch/pytorch/blob/master/.circleci/cimodel/data/dimensions.py#L14

Sorry, that folder is a bit over-engineered
