### ISSUE TITLE
Where are the windows CUDA builds?

### ISSUE THREAD

**Issue by scopatz** [pytorch/builder#522]
I see that windows is only built with CPU only on CI and the nightly crons don't build windows at all. I am curious where the windows release builds come from.

**Comment by soumith** [comment]
@peterjc123 would know.

**Comment by peterjc123** [comment]
Are you referring to the binary jobs? Actually, they are defined in pytorch/pytorch. A recent build can be seen here. https://app.circleci.com/pipelines/github/pytorch/pytorch/215758/workflows/a7cec706-e5fb-4487-a154-a2250e72badc

**Comment by peterjc123** [comment]
The config script of the jobs is located at
https://github.com/pytorch/pytorch/blob/master/.circleci/cimodel/data/binary_build_data.py

**Comment by scopatz** [comment]
Ahh OK, cool thanks. I'll look there.

**Comment by scopatz** [comment]
I am really looking for where the Windows machine gets configured to see how it is done. It looks like it might be at https://github.com/pytorch/pytorch/blob/master/.circleci/config.yml#L26

**Comment by walterddr** [comment]
yes the config.yml is the one-stop file, but it is generated based on the files in https://github.com/pytorch/pytorch/blob/master/.circleci/verbatim-sources

**Comment by walterddr** [comment]
closing this one. please feel free to reopen or use https://discuss.pytorch.org/ for general questions
