### ISSUE TITLE
[conda] Should ninja be a runtime dependency?

### ISSUE THREAD

**Issue by alanhdu** [pytorch/builder#530]
Right now, if you `conda install -c pytorch pytorch`, you also pull in `ninja` as a run-time dependency. I don't think this should be the case though -- Ninja is a build tool, so shouldn't it just be a build-time dependency?

I believe we can fix this by removing `ninja` from the run dependencies:

https://github.com/pytorch/builder/blob/bb24ca1110ce2d09700bfa29b8840535cb7d66e9/conda/pytorch-nightly/meta.yaml#L27-L31

**Comment by scopatz** [comment]
Yeah, I agree. Ninja should not be a runtime dep
