### ISSUE TITLE
Add builder integration tests that test the nightly build so that we can catch errors early

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/builder#833]
Related to issue https://github.com/pytorch/pytorch/issues/62754

We'd like to investigate how to better test builder PRs when it's only used in nightly builds.

**Comment by malfet** [comment]
Let's start small, by say integrating [binary_linux_manywheel_3_8m_cpu_devtoolset7_nightly_build](https://app.circleci.com/pipelines/github/pytorch/pytorch/383040/workflows/8527ecfe-b2ba-4086-9b76-87f0a0eb7b52/jobs/16120595)

**Comment by langong347** [comment]
#860

**Comment by seemethere** [comment]
Closing since we intend to track this in a different subproject
