### ISSUE TITLE
Standardize GHA binary linux build of a domain lib

### ISSUE THREAD

**Issue by langong347** [pytorch/builder#880]
Scope
- Binary linux build

This should solve the problems below:
- Create a reusable CI template for domain libs
- Currently each domain lib has its own copy of build scripts creating a maintenance problem

Execution strategy:
- Pick a candidate domain lib
- Extract the build scripts out of the domain lib and test
- Prototype the template based off `pytorch/pytorch` and test

**Comment by janeyx99** [comment]
Closing, cuz duplicate of https://github.com/pytorch/pytorch/issues/66656
