### ISSUE TITLE
There will be a regression in PR 950

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/builder#973]
#950  will trigger an exception at the very beginning of the windows conda build
```
+ cp -R 'C:\actions-runner\_work\pytorch\pytorch/pytorch' 'C:\actions-runner\_work\pytorch\pytorch/pytorch'
cp: cannot copy a directory, 'C:\actions-runner\_work\pytorch\pytorch/pytorch', into itself, 'C:\actions-runner\_work\pytorch\pytorch/pytorch/pytorch'
```
https://github.com/pytorch/pytorch/runs/5313907799?check_suite_focus=true#step:10:249

It could be fixed by https://github.com/mszhanyi/builder/blob/bb6d651214c92c4e70a581ed6327fed04cc5f112/conda/build_pytorch.sh#L165

I don't know the exact background of this PR. 
Please take a look.  @seemethere

**Comment by seemethere** [comment]
This should resolve https://github.com/pytorch/builder/pull/983
